### ISSUE TITLE
Don't automention when PR is still in draft mode

### ISSUE THREAD

**Issue by gaetanmaisse** [shilman/automention#15]
For me, a draft PR still need some dev/work and is not intended to be read/reviewed by others at this moment. So automention should not tag anybody until the PR has not been declared as `ready to review`. 

I face the situation on this PR: https://github.com/storybookjs/storybook/pull/7674

What's your opinion about it?

**Comment by gaetanmaisse** [comment]
Look's like `draft` flag on PR is in preview mode on Github API for now: https://developer.github.com/changes/2019-02-14-draft-pull-requests/

**Comment by shilman** [comment]
Good idea! I think draft PRs didn't exist when I created this. I'll add it now.

**Comment by shilman** [comment]
Should bd fixed here: https://github.com/shilman/automention/commit/e0f1ce2498f0eba30fc1a6df573f598b873dea9b
